version: '3.3'

services:
  upskill-server:
    image: "dineshvelhal/upskill-server:latest"
    container_name: "upskill-server"
    networks:
      - upskill_net
    ports:
      - "8000:8000"

  api-server:
    image: "dineshvelhal/json-server-demo:latest"
    container_name: "api-server"
    networks:
      - upskill_net
    ports:
      - "80:80"

networks:
  upskill_net:
